/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 public/models/World.gltf -o src/components/World.jsx -r public
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function World(props) {
  const { nodes, materials } = useGLTF('/models/World.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock1.geometry} material={materials['Grey.004']} position={[-61.103, -1.143, -44.66]} scale={5.198} />
      <mesh geometry={nodes.Rock2.geometry} material={materials['Grey.005']} position={[-25.226, -1.018, 48.516]} scale={5.462} />
      <mesh geometry={nodes.Rock3.geometry} material={materials['Grey.006']} position={[-11.843, -1.096, -30.626]} rotation={[0, 1.016, 0]} scale={11.095} />
      <mesh geometry={nodes.Rock4.geometry} material={materials['Grey.007']} position={[11.525, -1.096, 1.745]} scale={7.458} />
      <mesh geometry={nodes.Rock3001.geometry} material={materials['Grey.006']} position={[-76.586, -1.096, -28.945]} rotation={[Math.PI, -0.773, Math.PI]} scale={11.095} />
      <mesh geometry={nodes.Rock1001.geometry} material={materials['Grey.004']} position={[-21.583, -1.143, -59.092]} scale={5.198} />
      <mesh geometry={nodes.Rock1002.geometry} material={materials['Grey.004']} position={[-81.072, -1.143, 47.41]} rotation={[Math.PI, -0.088, Math.PI]} scale={5.198} />
      <mesh geometry={nodes.Rock4001.geometry} material={materials['Grey.007']} position={[-11.107, -1.096, 29.913]} rotation={[0, -0.428, 0]} scale={7.458} />
      <mesh geometry={nodes.Rock3002.geometry} material={materials['Grey.006']} position={[-55.775, -1.096, 29.913]} rotation={[0, 0.71, 0]} scale={11.095} />
      <mesh geometry={nodes.Rock3003.geometry} material={materials['Grey.006']} position={[-12.572, -1.096, -1.861]} rotation={[0, -1.124, 0]} scale={15.746} />
      <mesh geometry={nodes.Rock3004.geometry} material={materials['Grey.006']} position={[-77.637, -1.096, 7.841]} rotation={[0, -1.381, 0]} scale={12.84} />
      <mesh geometry={nodes.Rock2001.geometry} material={materials['Grey.005']} position={[-97.746, -1.018, -0.672]} rotation={[0, 1.492, 0]} scale={5.462} />
      <group position={[-11.546, 0.53, -9.576]} scale={3.463}>
        <mesh geometry={nodes.Cube026.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-11.546, 0.511, -13.102]} scale={3.463}>
        <mesh geometry={nodes.Cube027.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-11.546, 0.52, -16.65]} scale={3.463}>
        <mesh geometry={nodes.Cube028.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-38.425, 0.567, -43.959]} scale={3.463}>
        <mesh geometry={nodes.Cube029.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube029_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-75.475, 0.567, -39.964]} scale={3.463}>
        <mesh geometry={nodes.Cube030.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-97.514, 0.567, -24.122]} scale={3.463}>
        <mesh geometry={nodes.Cube031.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube031_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-77.291, 0.567, -2.55]} scale={3.463}>
        <mesh geometry={nodes.Cube032.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-66.757, 0.567, 30.867]} rotation={[0, -0.148, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube033.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-44.6, 0.567, 49.755]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube034.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube034_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-16.268, 0.567, 29.777]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube035.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube035_1.geometry} material={materials.Brown} />
      </group>
      <group position={[10.462, 0.544, -10.657]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube036.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube036_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-13.725, 0.567, -42.87]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube037.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube037_1.geometry} material={materials.Brown} />
      </group>
      <group position={[11.253, 0.567, -57.348]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube038.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube038_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-95.09, 0.567, 49.029]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube039.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube039_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-11.546, 4.063, -14.936]} scale={3.463}>
        <mesh geometry={nodes.Cube040.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube040_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-11.546, 4.342, -11.219]} rotation={[0.144, 0, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube041.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube041_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-11.546, 0.789, -20.453]} rotation={[-0.201, 0, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube042.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube042_1.geometry} material={materials.Brown} />
      </group>
      <group position={[11.035, 0.544, 36.839]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube043.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube043_1.geometry} material={materials.Brown} />
      </group>
      <mesh geometry={nodes.Sign_Left.geometry} material={materials['Brown.001']} position={[9.342, -1.195, -50.864]} scale={4.031} />
      <mesh geometry={nodes.Sign_Left001.geometry} material={materials['Brown.001']} position={[-82.914, -1.195, -59.33]} rotation={[0, 1.563, 0]} scale={4.031} />
      <mesh geometry={nodes.Sign_Left002.geometry} material={materials['Brown.001']} position={[-98.17, -1.195, 32.931]} rotation={[-Math.PI, 0.022, -Math.PI]} scale={4.031} />
      <mesh geometry={nodes.Sign_Left003.geometry} material={materials['Brown.001']} position={[-4.456, -1.195, 48.55]} rotation={[Math.PI, -1.558, Math.PI]} scale={4.031} />
      <group position={[-12.116, -1.257, 15.008]}>
        <mesh geometry={nodes.Cylinder008.geometry} material={materials['Brown.002']} />
        <mesh geometry={nodes.Cylinder008_1.geometry} material={materials.Green} />
      </group>
      <group position={[-11.123, -1.263, 8.754]} rotation={[0, -1.539, 0]} scale={1.65}>
        <mesh geometry={nodes.Cylinder007.geometry} material={materials['Brown.003']} />
        <mesh geometry={nodes.Cylinder007_1.geometry} material={materials['Green.001']} />
      </group>
      <group position={[-26.924, -1.232, -6.492]} scale={1.597}>
        <mesh geometry={nodes.Cylinder015.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder015_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[-10.025, -1.263, -25.374]} rotation={[0, -1.539, 0]} scale={1.65}>
        <mesh geometry={nodes.Cylinder001.geometry} material={materials['Brown.003']} />
        <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['Green.001']} />
      </group>
      <group position={[9.418, -1.263, -4.285]} rotation={[0, -1.539, 0]} scale={1.65}>
        <mesh geometry={nodes.Cylinder002.geometry} material={materials['Brown.003']} />
        <mesh geometry={nodes.Cylinder002_1.geometry} material={materials['Green.001']} />
      </group>
      <group position={[-29.19, -1.263, -45.695]} rotation={[0, -0.045, 0]} scale={1.65}>
        <mesh geometry={nodes.Cylinder003.geometry} material={materials['Brown.003']} />
        <mesh geometry={nodes.Cylinder003_1.geometry} material={materials['Green.001']} />
      </group>
      <group position={[-79.64, -1.263, -11.642]} rotation={[-Math.PI, 1.564, -Math.PI]} scale={1.65}>
        <mesh geometry={nodes.Cylinder004.geometry} material={materials['Brown.003']} />
        <mesh geometry={nodes.Cylinder004_1.geometry} material={materials['Green.001']} />
      </group>
      <group position={[9.897, -1.232, -16.091]} rotation={[0, 1.492, 0]} scale={1.597}>
        <mesh geometry={nodes.Cylinder005.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder005_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[-8.847, -1.232, -30.455]} rotation={[0, -1.392, 0]} scale={1.597}>
        <mesh geometry={nodes.Cylinder006.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder006_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[-36.267, -1.232, 32.338]} scale={1.597}>
        <mesh geometry={nodes.Cylinder009.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder009_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[-79.914, -1.232, 26.061]} rotation={[Math.PI, -1.567, Math.PI]} scale={1.597}>
        <mesh geometry={nodes.Cylinder010.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder010_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[-76.229, -1.257, 32.455]}>
        <mesh geometry={nodes.Cylinder011.geometry} material={materials['Brown.002']} />
        <mesh geometry={nodes.Cylinder011_1.geometry} material={materials.Green} />
      </group>
      <group position={[-96.829, -1.257, 40.653]} rotation={[0, 1.565, 0]}>
        <mesh geometry={nodes.Cylinder012.geometry} material={materials['Brown.002']} />
        <mesh geometry={nodes.Cylinder012_1.geometry} material={materials.Green} />
      </group>
      <group position={[-97.728, -1.263, 12.118]} rotation={[0, -1.532, 0]} scale={1.65}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials['Brown.003']} />
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['Green.001']} />
      </group>
      <group position={[-97.236, -1.232, -40.188]} rotation={[Math.PI, -1.553, Math.PI]} scale={1.597}>
        <mesh geometry={nodes.Cylinder014.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder014_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[-57.701, -1.232, -58.922]} scale={1.597}>
        <mesh geometry={nodes.Cylinder016.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[8.961, -1.232, 27.813]} rotation={[0, -1.516, 0]} scale={1.597}>
        <mesh geometry={nodes.Cylinder017.geometry} material={materials['Brown.004']} />
        <mesh geometry={nodes.Cylinder017_1.geometry} material={materials['Green.002']} />
      </group>
      <group position={[-54.005, -1.263, 47.096]} rotation={[0, 0.002, 0]} scale={1.65}>
        <mesh geometry={nodes.Cylinder018.geometry} material={materials['Brown.003']} />
        <mesh geometry={nodes.Cylinder018_1.geometry} material={materials['Green.001']} />
      </group>
      <group position={[-20.682, 0.567, 30.408]} rotation={[0, -0.025, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube048.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube048_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-72.853, 0.567, 28.345]} rotation={[0, -0.148, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube049.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube049_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-90.465, 0.567, 49.029]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube050.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube050_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-86.471, 0.567, 47.137]} rotation={[0, 0.291, 0]} scale={3.463}>
        <mesh geometry={nodes.Cube051.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube051_1.geometry} material={materials.Brown} />
      </group>
      <group position={[-40.221, 0.567, 47.712]} rotation={[Math.PI, -1.252, Math.PI]} scale={3.463}>
        <mesh geometry={nodes.Cube052.geometry} material={materials.DarkBrown} />
        <mesh geometry={nodes.Cube052_1.geometry} material={materials.Brown} />
      </group>
      <group position={[10.508, -1.234, -26.931]} scale={1.075}>
        <mesh geometry={nodes.Cube053.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Cube053_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube053_2.geometry} material={materials.LightRed} />
        <mesh geometry={nodes.Cube053_3.geometry} material={materials.RoofBlack} />
      </group>
      <group position={[9.963, 0.204, -23.278]} scale={1.371}>
        <mesh geometry={nodes.Cube054.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Cube054_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube054_2.geometry} material={materials.LightRed} />
      </group>
      <group position={[11.234, 3.01, -23.04]} scale={1.035}>
        <mesh geometry={nodes.Cube055.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube055_1.geometry} material={materials.LightRed} />
      </group>
      <group position={[9.798, 3.01, -23.029]} scale={1.035}>
        <mesh geometry={nodes.Cube056.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube056_1.geometry} material={materials.LightRed} />
      </group>
      <group position={[-78.781, -1.234, -17.686]} scale={1.075}>
        <mesh geometry={nodes.Cube057.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Cube057_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube057_2.geometry} material={materials.LightRed} />
        <mesh geometry={nodes.Cube057_3.geometry} material={materials.RoofBlack} />
      </group>
      <group position={[-46.16, -1.234, 30.471]} rotation={[0, -1.566, 0]} scale={1.075}>
        <mesh geometry={nodes.Cube058.geometry} material={materials.DarkRed} />
        <mesh geometry={nodes.Cube058_1.geometry} material={materials.White} />
        <mesh geometry={nodes.Cube058_2.geometry} material={materials.LightRed} />
        <mesh geometry={nodes.Cube058_3.geometry} material={materials.RoofBlack} />
      </group>
      <group position={[-47.178, -0.035, -44.757]} rotation={[0, 1.555, 0]}>
        <mesh geometry={nodes.Cylinder019.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.Cylinder019_1.geometry} material={materials['RoofBlack.001']} />
        <mesh geometry={nodes.Cylinder019_2.geometry} material={materials.LightBrown} />
        <mesh geometry={nodes.Cylinder019_3.geometry} material={materials['White.001']} />
        <mesh geometry={nodes.Cylinder019_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cylinder019_5.geometry} material={materials['Grey.008']} />
        <mesh geometry={nodes.Cylinder019_6.geometry} material={materials['DarkBrown.001']} />
      </group>
      <mesh geometry={nodes.TowerWindmill_Blades.geometry} material={materials.LightBrown} position={[-45.371, 7.404, -44.729]} rotation={[0, 1.555, 0]} />
      <group position={[-66.093, -0.035, 48.324]} rotation={[Math.PI, -1.565, Math.PI]}>
        <mesh geometry={nodes.Cylinder021.geometry} material={materials.DarkGrey} />
        <mesh geometry={nodes.Cylinder021_1.geometry} material={materials['RoofBlack.001']} />
        <mesh geometry={nodes.Cylinder021_2.geometry} material={materials.LightBrown} />
        <mesh geometry={nodes.Cylinder021_3.geometry} material={materials['White.001']} />
        <mesh geometry={nodes.Cylinder021_4.geometry} material={materials.Black} />
        <mesh geometry={nodes.Cylinder021_5.geometry} material={materials['Grey.008']} />
        <mesh geometry={nodes.Cylinder021_6.geometry} material={materials['DarkBrown.001']} />
      </group>
      <mesh geometry={nodes.TowerWindmill_Blades001.geometry} material={materials.LightBrown} position={[-67.9, 7.404, 48.314]} rotation={[Math.PI, -1.565, Math.PI]} />
      <group position={[9.124, -1.12, -32.402]} scale={1.913}>
        <mesh geometry={nodes.Cylinder023.geometry} material={materials['Grey.009']} />
        <mesh geometry={nodes.Cylinder023_1.geometry} material={materials['Brown.005']} />
        <mesh geometry={nodes.Cylinder023_2.geometry} material={materials['LightRed.001']} />
        <mesh geometry={nodes.Cylinder023_3.geometry} material={materials['White.002']} />
        <mesh geometry={nodes.Cylinder023_4.geometry} material={materials['DarkGrey.001']} />
      </group>
      <mesh geometry={nodes.Cube.geometry} material={materials['9C6542']} position={[-42.918, -1.975, -3.755]} scale={[1, 0.012, 1]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-7.992, -0.257, -47.748]} rotation={[0, 0, -Math.PI]} scale={[-0.06, -1, -0.095]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Material} position={[7.294, -0.257, -57.636]} rotation={[0, 0, -Math.PI]} scale={[-0.06, -1, -0.095]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.004']} position={[7.294, -0.257, -57.636]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.06, -1, -0.095]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.006']} position={[-95.622, -0.257, -57.636]} rotation={[0, 0, -Math.PI]} scale={[-0.06, -1, -0.095]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.002']} position={[7.294, -0.257, 45.028]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.06, -1, -0.095]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.005']} position={[-81.799, -0.257, -47.748]} rotation={[0, 0, -Math.PI]} scale={[-0.06, -1, -0.095]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.007']} position={[-7.992, -0.257, -47.748]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.06, -1, -0.095]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.003']} position={[-7.992, -0.257, 34.102]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-0.06, -1, -0.095]} />
    </group>
  )
}

useGLTF.preload('/models/World.gltf')
